name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v6

    - name: libgpiod
      run: |
        curl -S https://mirrors.edge.kernel.org/pub/software/libs/libgpiod/libgpiod-2.2.tar.gz -o libgpiod.tar.gz
        tar -xf libgpiod.tar.gz
        cd libgpiod-2.2/
        ./configure --enable-bindings-cxx
        make
        sudo make install
    
    - name: ads-1115-driver
      run: |
        git clone https://github.com/berndporr/rpi_ads1115.git
        cd rpi_ads1115/
        cmake .
        make
        sudo make install
      
    
    - name: make
      run: |
        cd application/
        make

    - name: package
      run: | 
        cd application/
        make deb

    - name: archive-binary
      uses: actions/upload-artifact@v6
      with:
        name: digitsynth-binary
        path: ./application/build/digitsynth

    - name: archive-package
      uses: actions/upload-artifact@v6
      with:
        name: digitsynth-package
        path: ./application/build/digitsynth-aarch64.deb

 
   
