name: C/C++ CI - RELEASE

on:
  push:
    branches: [ "release" ]

jobs:
  build:

    runs-on: ubuntu-24.04-arm
    outputs:
      tag: ${{ steps.generate-tag.outputs.tag }}

    steps:
    - uses: actions/checkout@v6

    - name: install-deps
      run: | 
        sudo ./install-deps.sh
   
    - name: make
      run: |
        cd application/
        make
   
    - name: package
      run: | 
        cd application/
        make deb

    - name: archive-binary
      uses: actions/upload-artifact@v6
      with:
        name: digitsynth-binary
        path: ./application/build/digitsynth

    - name: archive-package
      uses: actions/upload-artifact@v6
      with:
        name: digitsynth-package
        path: ./application/build/digitsynth-aarch64.deb
    
    - name: generate-tag
      id: generate-tag
      run: |
        echo "tag=$(cat ./VERSION)-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      shell: bash
    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ steps.generate-tag.outputs.tag }}"
        prerelease: false
        title: "DigitSynth Release"
        files: |            
          main
